name = "Snowy's Bolt Pack"
author = "Snowy893"
version = "v1.4.1+1.20.1"
description = "For playing the one-shot bow minigame!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38e366af6a5cefc8c5c53fa298cabfb6e84b7af4e8b7bde8eab4c78a38acc40c"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
